# frozen_string_literal: true

require "tmpdir"
require "archbuddy/config"
require "archbuddy/config/todo"

# v0.15 P1-T3: the todo document — dual entry shapes, milli-log2 integers,
# deterministic byte-stable generation.
RSpec.describe Archbuddy::Config::Todo do
  TodoFindingDouble = Struct.new(:rule, :file, :symbol, :value_raw, :components, keyword_init: true)

  def breaching(value)
    { value: value, threshold: 0, breached: true }
  end

  let(:findings) do
    [
      TodoFindingDouble.new(rule: "ExponentialNode", file: "app/models/user.rb",
                        symbol: "User#recalculate!", value_raw: 81),
      TodoFindingDouble.new(rule: "UseCaseComplexity", file: "app/api/api/v1/redeem_templates.rb",
                        symbol: "Api::V1::RedeemTemplates#PATCH[0]",
                        components: { "max_cone_node_log2" => breaching(13.0),
                                      "reach" => breaching(142) }),
      TodoFindingDouble.new(rule: "UseCaseDividend", file: "app/api/api/v1/redeem_templates.rb",
                        symbol: "Api::V1::RedeemTemplates#PATCH[0]",
                        components: { "dividend_log2" => breaching(Math.log2(8192)) }),
      TodoFindingDouble.new(rule: "FirewallBreaches", file: "app/api/api/v1/redeem_templates.rb",
                        symbol: "Api::V1::RedeemTemplates#PATCH[0]",
                        components: { "escapes" => breaching(3) }),
      # v0.16 debt-milli node entry (D-C5): (-score_raw × 1000).round for a
      # score_raw of -11.250 — a positive integer that grows as the node worsens.
      TodoFindingDouble.new(rule: "ReusabilityScore", file: "app/api/api/v1/points_products.rb",
                        symbol: "Api::V1::PointsProducts#POST[1]", value_raw: 11_250)
    ]
  end

  def generate(findings)
    described_class.generate(
      findings: findings,
      command_line: "archbuddy lint . --auto-gen-todo",
      tool_version: "archbuddy #{Archbuddy::VERSION}"
    )
  end

  it "generates both entry shapes with the R50 unit note (+ the v0.16 debt-milli line)" do
    text = generate(findings)
    expect(text).to include("# values are raw integers: native counts (mass, depth, reach, files, escapes, branches)")
    expect(text).to include("# or milli-log2 ((log2 x 1000).round) for *_millilog2 keys; display renders log2 to 1dp")
    expect(text).to include("# ReusabilityScore value: is debt milli ((-score_raw x 1000).round); grows as the node worsens")
    expect(text).to include("value: 81")
    expect(text).to include("value: 11250")
    expect(text).to include("values: { max_cone_node_millilog2: 13000, reach: 142 }")
    expect(text).to include("values: { escapes: 3 }")
  end

  it "milli-log2 encodes dividend 8192 → dividend_millilog2: 13000 exactly" do
    text = generate(findings)
    expect(text).to include("values: { dividend_millilog2: 13000 }")
  end

  it "round-trips byte-stably across BOTH entry shapes" do
    text = generate(findings)
    Dir.mktmpdir do |dir|
      path = File.join(dir, ".archbuddy_todo.yml")
      File.write(path, text)
      todo = described_class.load(path)
      regenerated = todo.regenerate(
        command_line: "archbuddy lint . --auto-gen-todo",
        tool_version: "archbuddy #{Archbuddy::VERSION}"
      )
      expect(regenerated).to eq(text)
    end
  end

  it "computes header counts (distinct nodes across rules)" do
    text = generate(findings)
    expect(text).to include("rule_count: 5")
    expect(text).to include("node_count: 3") # user.rb node + the redeem ep + the points_products node
  end

  it "emits YAML integers, never floats" do
    text = generate(findings)
    expect(text.scan(/value(?:s)?:.*\d+\.\d+/)).to eq([])
  end

  it "adds no timestamp by default; stamp: true adds exactly one line" do
    plain = generate(findings)
    expect(plain.scan(/^# Generated at:/).size).to eq(0)

    stamped = described_class.generate(
      findings: findings, command_line: "cmd", tool_version: "archbuddy x", stamp: true
    )
    expect(stamped.scan(/^# Generated at: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/).size).to eq(1)
  end

  it "generate(findings: []) writes the byte-exact empty document" do
    text = described_class.generate(
      findings: [], command_line: "archbuddy lint . --auto-gen-todo",
      tool_version: "archbuddy 0.12.0"
    )
    expect(text).to eq(<<~YAML)
      # Auto-generated by `archbuddy lint . --auto-gen-todo`
      # using archbuddy 0.12.0. Do not edit by hand; entries drop when violations heal.
      # values are raw integers: native counts (mass, depth, reach, files, escapes, branches)
      # or milli-log2 ((log2 x 1000).round) for *_millilog2 keys; display renders log2 to 1dp
      # ReusabilityScore value: is debt milli ((-score_raw x 1000).round); grows as the node worsens
      version: 1
      tool: "archbuddy 0.12.0"
      rule_count: 0
      node_count: 0
      rules: {}
    YAML
  end

  describe "#entry_for (I-P2' dual-shape)" do
    it "returns {value:} for node kinds, {values:} for use-case kinds, nil otherwise" do
      Dir.mktmpdir do |dir|
        path = File.join(dir, ".archbuddy_todo.yml")
        File.write(path, generate(findings))
        todo = described_class.load(path)

        expect(todo.entry_for("ExponentialNode", "app/models/user.rb", "User#recalculate!"))
          .to eq(value: 81)
        expect(todo.entry_for("ReusabilityScore", "app/api/api/v1/points_products.rb",
                              "Api::V1::PointsProducts#POST[1]"))
          .to eq(value: 11_250)
        expect(todo.entry_for("UseCaseComplexity", "app/api/api/v1/redeem_templates.rb",
                              "Api::V1::RedeemTemplates#PATCH[0]"))
          .to eq(values: { "max_cone_node_millilog2" => 13000, "reach" => 142 })
        expect(todo.entry_for("ExponentialNode", "other.rb", "X#y")).to be_nil

        empty = described_class.generate(findings: [], command_line: "c", tool_version: "t")
        File.write(path, empty)
        loaded = described_class.load(path)
        expect(loaded.entry_for("ExponentialNode", "app/models/user.rb", "User#recalculate!")).to be_nil
      end
    end
  end
end
